version: '3.8'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile_DB
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
