version: '3.8'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile_DB
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
